### ISSUE TITLE
[Refactor] 구매 관련 변동 사항(ERD)

### ISSUE THREAD

**Issue by jycforest29** [LastMinuteMarket/LastMinute-Server#3]
- Purchase 테이블 변동
![스크린샷 2023-06-03 21-29-55](https://github.com/LastMinuteMarket/LastMinute-Server/assets/103106183/cf42ff60-a34a-4da3-a4e6-d35608e37113)
- PgAgency 어댑터 제거
PurchaseService에서 바로 Pg사에서 결제하는 것처럼, 결제 관련 CRD를 제공할 생각입니다.

**Comment by gimangi** [comment]
저도 동의합니다!
어댑터는 제거하고, PgAgency 인터페이스를 만들어서 purchase 메서드를 두는 것은 어떨까요
테스트 시나 데모 때에도 그냥 mock 인스턴스 만들어서 적용할 수 있을 것 같습니다!

**Comment by jycforest29** [comment]
넵 저도 그렇게 하는 것이 좋을 것 같습니다. 해당 부분 수정 후 풀 리퀘 올리겠습니다~
