### ISSUE TITLE
진행상황 요약

### ISSUE THREAD

**Issue by jycforest29** [LastMinuteMarket/LastMinute-Server#8]
- 남은 부분
 - purchase
    - `@Scheduled`로 State 변경
  - user
    - UserService에서 회원가입, 로그인 만들고 기존 시큐리티 설정과 통합해 테스트
    - 컨트롤러 계층 수정 (시큐리티 홀더에서 id 꺼내기)
  - 채팅
    - 구현 예정(메시징 큐 x. 웹 소켓 + dto 사용)

- 예상 일정
화요일 오전까지 로컬에서 모든 기능 돌아가게 구현 & 테스트 (주연)
수요일 오전까지 aws 환경에서 테스트, 앱 부분 제외 문서화 및 발표자료 준비 (한혜, 주연)
수요일 오후부터 앱 구현, 앱과 연동 후 테스트 (형기, 주연)

**Comment by gimangi** [comment]
[product]
- 가격 스케쥴링 (00시 배치 적용 예정)
- 좋아요 기능 (비관적 락 적용 예정)
- 이미지 업로드 (기능개발 후순위로, 데모 때 꼭 포함하지 않아도 됨)
- 구매 후 ProductState를 SOLD_OUT으로 변경 (필터링은 구현되어 있음)
